---
- name: Install development tools package group
  yum: name="@Development tools" state=present update_cache=yes

- name: Install kernel dev packages
  yum: name={{ item }} state=present
  with_items: 
  - ncurses-devel
  - bc
  - openssl-devel
  - hmaccalc
  - zlib-devel
  - binutils-devel
  - elfutils-libelf-devel

- name: Download kernel
  get_url:
    url: https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.23.tar.xz
    dest: /tmp/linux-{{ kernel_ver }}.tar.xz

- name: Untar kernel
  unarchive: src=/tmp/linux-{{ kernel_ver }}.tar.xz dest=/tmp/linux-{{ kernel_ver }}

- name: copy kernel config file for make
  copy: src=kernel.config dest=/tmp/linux-{{ kernel_ver }}/.config

- name: Install kernel
  shell: "{{ item }}"
  with_items:
  - make silentoldconfig .config
  - make 
  - make modules
  - make modules_install
  - make install
  args:
    chdir: /tmp/linux-{{ kernel_ver }}/

- name: restart machine
  shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  become: false

- name: Rerun make install to correct grub entry order
  shell: make install 
  args:
    chdir: /tmp/linux-{{ kernel_ver }}/

- name: Restart machine
  shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: Wait for host to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  become: false
 
- name: Register kernel version
  shell: uname -a
  register: kernel_version
  failed_when: "{{ kernel_ver }} not in kernel_version"

- name: Print final kernel version
  debug: var=kernel_version.stdout
