---
- name: Install development tools package group
  # The raw yum group does not work since switch to rhel ccs-mirror from centos. Reduced total rpms too.
  # yum: name="@Development tools" state=present update_cache=yes --> does not work using internal repos
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - bison
    - byacc
    - cscope
    - ctags
    - flex
    - gcc
    - gcc-c++
    - git
    - libtool
    - patch
    - patchutils
    - swig

# There is a conflict between the vagrant box anaconda install and what is avail on the ccs-mirror repos
# This isn't a problem on the physical servers that we kickstarted on 12/1/16; but this should work for
# both --> if it does not then we can just resolve it in the local_dev/Vagrantfile instead.
- name: Downgrade krb5-libs
  shell: yum downgrade krb5-libs -y

- name: Install kernel dev packages
  yum: name={{ item }} state=present
  with_items: 
  - ncurses-devel
  - bc
  - openssl-devel
  - hmaccalc
  - zlib-devel
  - binutils-devel
  - elfutils-libelf-devel

- name: Download kernel
  get_url:
    url: https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.23.tar.xz
    dest: /tmp/linux-{{ kernel_ver }}.tar.xz

- name: Untar kernel
  shell: tar -Jxvf linux-{{ kernel_ver }}.tar.xz
  args:
    chdir: /tmp/

- name: copy kernel config file for make
  copy: src=kernel.config dest=/tmp/linux-{{ kernel_ver }}/.config

- name: Install kernel
  shell: "{{ item }}"
  with_items:
  - make silentoldconfig .config
  - make -j{{ cpus }} 
  - make -j{{ cpus }} modules
  - make -j{{ cpus }} modules_install
  - make install
  args:
    chdir: /tmp/linux-{{ kernel_ver }}/

- name: restart machine
  shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  become: false

- name: Rerun make install to correct grub entry order
  shell: make install 
  args:
    chdir: /tmp/linux-{{ kernel_ver }}/

- name: Restart machine
  shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for host to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  become: false
 
- name: Regather fact filtering for ansible_kernel
  setup: filter='ansible_kernel'

- name: Check kernel is at the correct version
  assert: 
    that: "'{{ kernel_ver }}' == '{{ ansible_kernel }}'"

- name: Print final kernel version
  debug: var=ansible_kernel
